### PR TITLE
Adds code and test to redirect from map when not logged in.

### PR DESCRIPTION
**Pull request by RyannWilcox**
I added the test and code for that redirect thing we were talking about today.

### CODE REVIEW

**Comment by fergyfresh** [comment]
I still want the other test. Put that back in and I'll accept the pull.

**Comment by fergyfresh** [comment]
Also, take the other two shitty tests out.

**Comment by RyannWilcox** [comment]
hahah I figured you would say that

**Comment by RyannWilcox** [comment]
should be good now...

**Comment by fergyfresh** [comment]
Yupp. Thanks!

**Pull request merged**
